commit

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,5 +1,8 @@
 FROM quay.io/centos/centos:stream8
 
-RUN dnf install -y python3-pip && \
-    pip3 install --user podman ansible && \
+RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf && \
+    dnf install -y python3-pip && \
+    pip3 install podman ansible && \
     dnf clean all
+
+RUN curl -s https://www.google.com > /dev/null || echo "Network error"
